source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def pods
    pod 'FSPagerView'
    pod 'IQKeyboardManagerSwift'
    pod 'Alamofire'
  # 'node_modules'目录一般位于根目录中
  # 如果你的RN版本 >= 0.42.0，请加入下面这行
#  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#  'Core',
#  'CxxBridge', # 如果RN版本 >= 0.45则加入此行
#  'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
#  'RCTText',
#  'RCTNetwork',
#  'RCTWebSocket', # 这个模块是用于调试功能的
#  # 在这里继续添加你所需要的RN模块
#  ]
#  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
#  # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

target 'RNSwiftDemo' do
    pods
#  pod 'CodePush', :path => '../node_modules/react-native-code-push'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

